#!/usr/bin/env bash

loggedInUser=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' )

mv /Applications/Notion.app /Users/$loggedInUser/Applications/Notion.app