#!/usr/bin/env bash

loggedInUser=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' )

chown -R $loggedInUser: /Applications/Slack.app/ && chmod -R 775 /Applications/Slack.app/